### ISSUE TITLE
libfranka: Connection to FCI refused. Please install FCI feature or enable FCI mode in Desk.

### ISSUE THREAD

**Issue by stonfute** [marcbone/liborl#6]
Hello, 
thanks for your work.
I have a small problem. 

Everything works fine with libfranka, but when using liborl I've this error when i tried any example
`libfranka: Connection to FCI refused. Please install FCI feature or enable FCI mode in Desk.`

Any idea ?

**Comment by marcbone** [comment]
Are you sure you are connecting to the correct ip address and have FCI enabled in Desk?

**Comment by stonfute** [comment]
yeah ! Everything works fine when I use libfranka alone

**Comment by marcbone** [comment]
This is very confusing. So this error can only happen when libfranka tries to connect to a wrong computer or a  robot that does not have fci enabled. Can you tell me what you are running? Or try out one of the examples of liborl?

**Comment by stonfute** [comment]
Yes, I tried several examples and always the same results. No other cue since everything work fine with libfranka standalone.
some info about config : ubuntu 22.04, libfranka 9.2, firmware 4.2.2

**Comment by marcbone** [comment]
Ok I think I got it. liborl also connects to the gripper. You dont have a gripper attached, right?

**Comment by stonfute** [comment]
oh yeah ! that's it ! Thanks for the hint
