### ISSUE TITLE
How to print the pose?

### ISSUE THREAD

**Issue by AndingDrLin** [marcbone/liborl#7]
Hi! I am wondering that how can I print out the pose of end effector for calibration using "get_current_pose()"?

**Comment by marcbone** [comment]
seem like i didnt implenment the `<<` operator properly. But you should be able to do:

```c++
std::cout << robot.get_current_pose.toString() << std::endl;
```

**Comment by AndingDrLin** [comment]
Thank you! I have already find this function from the source code. (´▽`ʃ♡ƪ)
